on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Pipeline
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          url: ${{secrets.APPBASEIOURL}}
          file: "./examples/pipe.yaml"
        env:
          TEST_KEY: ${{secrets.APPBASEIOURL}}